apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: 707913648704.dkr.ecr.us-east-1.amazonaws.com/product-service:e8ad237
    spec:
      containers:
        - name: cart-service
          image: 
          ports:
            - containerPort: 3001
