apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: image: 707913648704.dkr.ecr.us-east-1.amazonaws.com/product-service:a4aee9f
          ports:
            - containerPort: 3001
